/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nigfe
 */
import java.text.DecimalFormat;
import java.io.*;
import java.util.*;
public class gradesApp extends javax.swing.JFrame {
    private int i = 0;
    private int j = 0;
    private String[][] studentCredentials = new String[29][6];
    /**
     * Creates new form gradesApp
     */
    public gradesApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldTest1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFieldLastName = new javax.swing.JTextField();
        txtFieldFirstName = new javax.swing.JTextField();
        txtFieldTest2 = new javax.swing.JTextField();
        txtFieldTest3 = new javax.swing.JTextField();
        txtFieldTest4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDisplay = new javax.swing.JTextArea();
        add = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnStudentAverage = new javax.swing.JButton();
        btnCourseAverage = new javax.swing.JButton();
        textFieldListDisplay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Students Grade");

        jLabel2.setText("First name:");

        jLabel3.setText("Test 1");

        jLabel4.setText("Test 1");

        jLabel5.setText("Test 1");

        jLabel6.setText("Test 1");

        txtFieldTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTest1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Last name:");

        txtFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldLastNameActionPerformed(evt);
            }
        });

        txtFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldFirstNameActionPerformed(evt);
            }
        });

        txtFieldTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTest2ActionPerformed(evt);
            }
        });

        txtFieldTest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTest3ActionPerformed(evt);
            }
        });

        txtFieldTest4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTest4ActionPerformed(evt);
            }
        });

        textAreaDisplay.setColumns(20);
        textAreaDisplay.setRows(5);
        jScrollPane1.setViewportView(textAreaDisplay);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnStudentAverage.setText("Student Average");
        btnStudentAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentAverageActionPerformed(evt);
            }
        });

        btnCourseAverage.setText("Course Average");
        btnCourseAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseAverageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtFieldTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFieldTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFieldTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFieldTest4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCourseAverage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnStudentAverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldListDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFieldTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFieldTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnList)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldTest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFieldTest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStudentAverage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCourseAverage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldListDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTest1ActionPerformed

    private void txtFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldLastNameActionPerformed

    private void txtFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldFirstNameActionPerformed

    private void txtFieldTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTest2ActionPerformed

    private void txtFieldTest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTest3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTest3ActionPerformed

    private void txtFieldTest4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTest4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTest4ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // Get the current content of textAreaDisplay
        String currentContent = textAreaDisplay.getText();

        // Get input values from your text fields
        String firstName = txtFieldFirstName.getText();
        String lastName = txtFieldLastName.getText();
        String test1 = txtFieldTest1.getText();
        String test2 = txtFieldTest2.getText();
        String test3 = txtFieldTest3.getText();
        String test4 = txtFieldTest4.getText();

        // Check if the combination of first name and last name already exists
        boolean studentExists = false;
        for (int row = 0; row < i; row++) {  // Only check existing entries
            if (firstName.equals(studentCredentials[row][0]) && lastName.equals(studentCredentials[row][1])) {
                studentExists = true;
                break;
            }
        }

        // Check if the input for grades is valid (doubles)
        boolean validGrades = true;
        try {
            Double.parseDouble(test1);
            Double.parseDouble(test2);
            Double.parseDouble(test3);
            Double.parseDouble(test4);
        } catch (NumberFormatException e) {
            validGrades = false;
        }

        // Check for other error conditions
        if (studentExists) {
            textFieldListDisplay.setText("Student already exists");
        } else if (!validGrades) {
            textFieldListDisplay.setText("You must enter a number for the grades");
        } else if (i >= studentCredentials.length) {
            textFieldListDisplay.setText("Class is at capacity");
        } else if (firstName.isEmpty() || lastName.isEmpty() || test1.isEmpty() || test2.isEmpty() || test3.isEmpty() || test4.isEmpty()) {
            textFieldListDisplay.setText("Fill in all text fields please");
        } else {
            // If everything is okay, add the data to the array
            studentCredentials[i][0] = firstName;
            studentCredentials[i][1] = lastName;
            studentCredentials[i][2] = test1;
            studentCredentials[i][3] = test2;
            studentCredentials[i][4] = test3;
            studentCredentials[i][5] = test4;

            // Append the data to textAreaDisplay with a new line
            currentContent += "[" + firstName + ", " + lastName + ", " + test1 + ", " + test2 + ", " + test3 + ", " + test4 + "]\n";

            // Increment the row for the next entry
            i++;
        }

        // Set the updated content in textAreaDisplay
        textAreaDisplay.setText(currentContent);


    }//GEN-LAST:event_addActionPerformed


    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        StringBuilder displayText = new StringBuilder();

        for (int row = 0; row < studentCredentials.length; row++) {
            if (studentCredentials[row][0] != null) {
                displayText.append("[");
                for (int col = 0; col < studentCredentials[row].length; col++) {
                    displayText.append("\"").append(studentCredentials[row][col]).append("\"");
                    if (col < studentCredentials[row].length - 1) {
                        displayText.append(", ");
                    }
                }
                displayText.append("]\n");
            }
        }

        // Set the display text in the textFieldListDisplay
        textFieldListDisplay.setText(displayText.toString());
    }//GEN-LAST:event_btnListActionPerformed

    private void btnStudentAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentAverageActionPerformed
    // Get input values from your text fields
    String firstName = txtFieldFirstName.getText();
    String lastName = txtFieldLastName.getText();

    double testSum = 0;
    int testCount = 0;

    for (int row = 0; row < studentCredentials.length; row++) {
        if (studentCredentials[row][0] != null && studentCredentials[row][1] != null
                && studentCredentials[row][0].equals(firstName) && studentCredentials[row][1].equals(lastName)) {
            // Iterate through the test scores and calculate the sum
            for (int col = 2; col < studentCredentials[row].length; col++) {
                if (studentCredentials[row][col] != null) {
                    testSum += Double.parseDouble(studentCredentials[row][col]);
                    testCount++;
                }
            }
            break; // Found the student, no need to continue searching
        }
    }

    if (testCount > 0) {
        double studentAverage = testSum / testCount;
        DecimalFormat decimalFormat = new DecimalFormat("#.00");
        String formattedAverage = decimalFormat.format(studentAverage);
        textFieldListDisplay.setText(firstName + " " + lastName + "'s average is " + formattedAverage + "%");
    } else {
        textFieldListDisplay.setText("Student not found or has no test scores.");
    }
    }//GEN-LAST:event_btnStudentAverageActionPerformed

    private void btnCourseAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseAverageActionPerformed
        // TODO add your handling code here:
        double testSum = 0;
        int testCount = 0;
        for (int row = 0; row < studentCredentials.length; row++) {
            if (studentCredentials[row][0] != null && studentCredentials[row][1] != null) {
                // Iterate through the test scores and calculate the sum
                for (int col = 2; col < studentCredentials[row].length; col++) {
                    if (studentCredentials[row][col] != null) {
                        testSum += Double.parseDouble(studentCredentials[row][col]);
                        testCount++;
                    }
                }            }
    }
        double courseAverage = testSum / testCount;
        DecimalFormat decimalFormat = new DecimalFormat("#.00");
        String formattedAverage = decimalFormat.format(courseAverage);
        textFieldListDisplay.setText("The course average is " + formattedAverage + "%");
    }//GEN-LAST:event_btnCourseAverageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gradesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gradesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gradesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gradesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gradesApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton btnCourseAverage;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnStudentAverage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaDisplay;
    private javax.swing.JTextField textFieldListDisplay;
    private javax.swing.JTextField txtFieldFirstName;
    private javax.swing.JTextField txtFieldLastName;
    private javax.swing.JTextField txtFieldTest1;
    private javax.swing.JTextField txtFieldTest2;
    private javax.swing.JTextField txtFieldTest3;
    private javax.swing.JTextField txtFieldTest4;
    // End of variables declaration//GEN-END:variables
}
